### ISSUE TITLE
Not loading from local (Binary release dev-20210927a)

### ISSUE THREAD

**Issue by dggfi** [viktor-ferenczi/EnhancedUI#9]
Context: No server running, tested read from `Content/Termina.html.` Got an empty page.

![image](https://user-images.githubusercontent.com/91400038/134830437-27f6fc5d-c028-4a19-9ed2-12cfd3618df2.png)

![image](https://user-images.githubusercontent.com/91400038/134830445-4500f2e9-155f-4df9-b9c3-eec6324a1ec0.png)

Contrarily, the page loads fine when querying from `localhost:3000` and loading the response. So,

reading from local: bad
reading from server: good

**Comment by dggfi** [comment]
Amendment: It's completely irregular even with the server. But I have only had success with the server.

**Comment by viktor-ferenczi** [comment]
Reproduced with local file. Sometimes the content loads, sometime it does not. Seems to be a timing issue, need to debug.

**Comment by viktor-ferenczi** [comment]
Looks like it is using a single video player with `VideoName = "CefFrame"` to display the UI for both the Control Panel and the Inventory tabs, which is wrong. It mixes them up and whether it works depends on the initialization order.

**Comment by viktor-ferenczi** [comment]
Putting this ticket on hold, since the plan has change to use a single browser overlay over the whole game's screen. Therefore we don't need to support separate browsers per each tab.
